// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfKvWt0Gil4KUWXmNJLO5Vz9e42T7J7lM',
    appId: '1:868727018100:web:2365125527fc5e1993b721',
    messagingSenderId: '868727018100',
    projectId: 'tiktokclone-fc5d8',
    authDomain: 'tiktokclone-fc5d8.firebaseapp.com',
    storageBucket: 'tiktokclone-fc5d8.appspot.com',
    measurementId: 'G-TKF5N6K22D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1IfYwYfhAbfGINFyol8KSkelLOxp2nnM',
    appId: '1:868727018100:android:9230227af2d14b1e93b721',
    messagingSenderId: '868727018100',
    projectId: 'tiktokclone-fc5d8',
    storageBucket: 'tiktokclone-fc5d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApUVDE01cHsExmtM5leGwxr9CgBaUE1U4',
    appId: '1:868727018100:ios:229a1f24bd94bcfd93b721',
    messagingSenderId: '868727018100',
    projectId: 'tiktokclone-fc5d8',
    storageBucket: 'tiktokclone-fc5d8.appspot.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
